// <auto-generated />
using BioskopWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BioskopWebApi.Migrations
{
    [DbContext(typeof(BioskopContext))]
    [Migration("20210116010920_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BioskopWebApi.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("BrojSale")
                        .HasColumnType("int")
                        .HasColumnName("BrojSale");

                    b.Property<int>("CenaKarte")
                        .HasColumnType("int")
                        .HasColumnName("CenaKarte");

                    b.Property<string>("DatumProjekcije")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DatumProjekcije");

                    b.Property<string>("NazivFilma")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NazivFilma");

                    b.Property<string>("VremeProjekcije")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VremeProjekcije");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.HasKey("ID");

                    b.ToTable("BioskopskaSala");
                });

            modelBuilder.Entity("BioskopWebApi.Models.VipKartica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int>("JMBG")
                        .HasColumnType("int")
                        .HasColumnName("JMBG");

                    b.Property<string>("Prezime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Prezime");

                    b.Property<string>("VrstaKartice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("VrstaKartice");

                    b.Property<string>("eMail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eMail");

                    b.HasKey("ID");

                    b.ToTable("VipKartica");
                });
#pragma warning restore 612, 618
        }
    }
}
